image: jangrewe/gitlab-ci-android

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - export BUILD_NUMBER=$(git rev-list --count ${CI_BUILD_REF})
  - export BUILD_COMMIT_SHA=${CI_COMMIT_SHA}
  - chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

stages:
  - code_quality
  - test
  - build

lint:
  stage: code_quality
  script:
    - ./gradlew lintDebug
  artifacts:
    when: on_failure
    name: "lint_${BUILD_NUMBER}_${BUILD_COMMIT_SHA}"
    expire_in: 1 days
    paths:
      - app/build/reports/lint-results-debug.xml
  only:
    - merge_requests

ktlint:
  stage: code_quality
  script:
    - ./gradlew ktlint
  artifacts:
    when: on_failure
    name: "ktlint_${BUILD_NUMBER}_${BUILD_COMMIT_SHA}"
    expire_in: 1 days
    paths:
      - app/build/reports/checkstyle/ktlint-report.xml
  only:
    - merge_requests

unitTests:
  stage: test
  script:
    - ./gradlew test
  only:
    - merge_requests

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}"
    paths:
      - app/build/outputs/
  only:
    - merge_requests