image: jangrewe/gitlab-ci-android:28

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

stages:
  - code_quality
  - test
  - build

lint:
  stage: code_quality
  script:
    - ./gradlew lintDebug
  artifacts:
    when: on_failure
    name: "lint_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    expire_in: 1 days
    paths:
      - app/build/reports/lint-results-debug.xml
  only:
    - merge_requests

ktlint:
  stage: code_quality
  script:
    - ./gradlew ktlint
  artifacts:
    when: on_failure
    name: "ktlint_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    expire_in: 1 days
    paths:
      - app/build/reports/checkstyle/ktlint-report.xml
  only:
    - merge_requests

unitTests:
  stage: test
  script:
    - ./gradlew testDebugUnitTest
  artifacts:
    when: on_failure
    name: "unitTests_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    expire_in: 1 days
    paths:
      - app/build/reports/tests/
  only:
    - merge_requests

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    name: "build_${CI_PROJECT_NAME}+${CI_COMMIT_REF_NAME}"
    expire_in: 1h
    paths:
      - app/build/outputs/
  only:
    - merge_requests